# Generated by Django 4.2.15 on 2024-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccess',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
