# Generated by Django 4.2.15 on 2024-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_app', '0002_emailaccess_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccess',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
