# Generated by Django 4.2.15 on 2024-08-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_app', '0003_emailaccess_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccess',
            name='file',
        ),
    ]
