# Generated by Django 4.2.15 on 2024-08-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_app', '0004_remove_emailaccess_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccess',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
    ]
